[package]
name = "okf"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(fw, values("1100"))'] }

[dependencies]
bitflags = "2.5.0"
okf-macros = { version = "0.1.0", path = "macros" }

[workspace]
members = [
    "kernel-1100",
    "macros"
]
